---
networks:
  discovery:
    external: true

services:
  nut:
    image: teknologist/webnut
    container_name: webnut
    restart: unless-stopped

    networks:
      - proxy

    security_opt:
      - no-new-privileges:true
    ports:
      - 6543:6543

    environment:
      - UPS_HOST=ip.address.of.nut.server
      - UPS_PORT=3493
      - UPS_USER=admin
      - UPS_PASSWORD=secret
