---
services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync

    environment:
      - PRIMARY=${PRIMARY_HOST_URL}|${PIHOLE_ADMIN_PASSWORD}
      - REPLICAS=${SECONDARY_HOST_1_URL}|${PIHOLE_ADMIN_PASSWORD}
      - FULL_SYNC=true
      - RUN_GRAVITY=true
      - CRON=*/15 * * * *
      - CLIENT_SKIP_TLS_VERIFICATION=true
      - TZ=Asia/Colombo
      - SYNC_CONFIG_DNS=true
      - SYNC_CONFIG_DHCP=false
      - SYNC_CONFIG_NTP=false
      - SYNC_CONFIG_RESOLVER=false
      - SYNC_CONFIG_DATABASE=false
      - SYNC_CONFIG_MISC=false
      - SYNC_CONFIG_DEBUG=false
      - SYNC_GRAVITY_DHCP_LEASES=false
      - SYNC_GRAVITY_GROUP=false
      - SYNC_GRAVITY_AD_LIST=true
      - SYNC_GRAVITY_AD_LIST_BY_GROUP=true
      - SYNC_GRAVITY_DOMAIN_LIST=true
      - SYNC_GRAVITY_DOMAIN_LIST_BY_GROUP=true
      - SYNC_GRAVITY_CLIENT=false
      - SYNC_GRAVITY_CLIENT_BY_GROUP=false
