---
services:
  db:
    image: mariadb:11.5.2
    restart: unless-stopped
    volumes:
      - ${SERVICE_DIR}/db_data:/var/lib/mysql
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - TIMEZONE=${TIMEZONE}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 1s
      retries: 5

  snipe-it:
    image: lscr.io/linuxserver/snipe-it:latest
    container_name: snipe-it
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - APP_KEY=${APP_KEY}
      - APP_URL=https://snipeit.local.theinquisitive.me
      - MYSQL_PORT_3306_TCP_ADDR=db
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - APP_DEBUG=false #optional
      - APP_ENV=production #optional
      - APP_FORCE_TLS=false #optional
      - APP_LOCALE= #optional
      - MAIL_PORT_587_TCP_ADDR=${MAIL_PORT_587_TCP_ADDR}
      - MAIL_PORT_587_TCP_PORT=587
      # - MAIL_ENV_FROM_ADDR= #optional
      # - MAIL_ENV_FROM_NAME= #optional
      # - MAIL_ENV_ENCRYPTION= #optional
      # - MAIL_ENV_USERNAME= #optional
      # - MAIL_ENV_PASSWORD= #optional
    volumes:
      - ${SERVICE_DIR}/config:/config
    ports:
      - 8080:80
    restart: unless-stopped
