services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    restart: unless-stopped

    ports:
      - '8282:80/tcp'

    environment:
      TZ: 'Asia/Colombo'

    # Volumes store your data between container upgrades
    volumes:
      - ${SERVICE_DIR}/db:/var/www/html/db
      - ${SERVICE_DIR}/logos:/var/www/html/images/uploads/logos
