---
services:
  pi.alert:
    container_name: Pi.Alert
    mem_limit: 2g
    cpu_shares: 768

    network_mode: host
    
    image: jokobsk/pi.alert:latest
    restart: on-failure:5

    ports:
      - '20211:20211'

    security_opt:
      - no-new-privileges:true

    volumes:
      - ${SERVICE_DIR}/config:/home/pi/pialert/config:rw
      - ${SERVICE_DIR}/pialert/db:/home/pi/pialert/db:rw
      - ${SERVICE_DIR}/logs:/home/pi/pialert/front/log:rw

    environment:
      - TIMEZONE=Asia/Colombo
      - PORT=20211
      - HOST_USER_ID=1000
      - HOST_USER_GID=1000

    healthcheck:
      test: curl -f http://localhost:20211/ || exit 1