http:
  routers:
    epson-printer:
      entryPoints:
        - websecure
      rule: Host(`printer.local.theinquisitive.me`)
      tls: {}
      service: epson-printer
    brother-scanner:
      entryPoints:
        - websecure
      rule: Host(`scanner.local.theinquisitive.me`)
      tls: {}
      service: brother-scanner

  services:
    epson-printer:
      loadBalancer:
        servers:
          - url: https://172.16.30.9
        passHostHeader: true
    brother-scanner:
      loadBalancer:
        servers:
          - url: http://172.16.30.10
        passHostHeader: true
