services:
  orbital-sync:
    image: mattwebbio/orbital-sync:1
    restart: unless-stopped

    container_name: orbital-sync

    environment:
      PRIMARY_HOST_BASE_URL: ${PRIMARY_HOST_BASE_URL}
      PRIMARY_HOST_PASSWORD: ${PIHOLE_ADMIN_PASSWORD}
      SECONDARY_HOST_1_BASE_URL: ${SECONDARY_HOST_1_BASE_URL}
      SECONDARY_HOST_1_PASSWORD: ${PIHOLE_ADMIN_PASSWORD}
      INTERVAL_MINUTES: 15
      NOTIFY_ON_SUCCESS: false
      NOTIFY_ON_FAILURE: true
      VERBOSE: true
