---
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped

    ports:
      - 53:53/tcp
      - 53:53/udp
      #   - '67:67/udp'
      - 80:80/tcp

    environment:
      TZ: 'Asia/Colombo'
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_dns_upstreams: ${PIHOLE_DNS_UPSTREAMS}
      FTLCONF_dns_revServers: ${PIHOLE_DNS_REVERSE_SERVERS}
      FTLCONF_webserver_api_password: ${PIHOLE_WEBPASSWORD}
      FTLCONF_webserver_domain: ${PIHOLE_WEBSERVER_DOMAIN}
      PIHOLE_UID: ${USER_ID}
      PIHOLE_GID: ${GROUP_ID}

    volumes:
      - '${SERVICE_DIR}/etc-pihole/:/etc/pihole/'
      - '${SERVICE_DIR}/etc-dnsmasq.d/:/etc/dnsmasq.d/'

    cap_add:
      - CAP_SYS_TIME
      - CAP_SYS_NICE
    #   - NET_ADMIN
