---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    
    ports:
      - "32400:32400"
      - "1900:1900/udp"
      - "5353:5353/udp"
      - "8324:8324"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "32469:32469"

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Asia/Colombo
      - VERSION=docker
      - PLEX_CLAIM=claim-Miy9k57fhVE91jS2xjEg
      
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SERVICE_DIR}/config:/config
      - ${REMOTE_DATA_DIR}/data/media:/data/media:ro