---
services:
  broker:
    image: docker.io/library/redis:8
    restart: unless-stopped

    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:17
    restart: unless-stopped

    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

    volumes:
      - ${SERVICE_DIR}/pgdata:/var/lib/postgresql/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika

    ports:
      - '8000:8000'

    volumes:
      - ${REMOTE_MOUNT_DIR}/data:/usr/src/paperless/data
      - ${REMOTE_MOUNT_DIR}/media:/usr/src/paperless/media
      - ${SERVICE_DIR}/export:/usr/src/paperless/export
      - ${SERVICE_DIR}/consume:/usr/src/paperless/consume

    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_URL: https://${SERVICE_URL}
      # PAPERLESS_CSRF_TRUSTED_ORIGINS: 'https://*.local.theinquisitive.me'
      # PAPERLESS_CORS_ALLOWED_HOSTS: ${SERVICE_URL}
      # PAPERLESS_ALLOWED_HOSTS: ${SERVICE_URL}
      USERMAP_UID: 3004
      USERMAP_GID: 3004

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.20
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - 'gotenberg'
      - '--chromium-disable-javascript=true'
      - '--chromium-allow-list=file:///tmp/.*'

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

volumes:
  redisdata:
