---
networks:
  discovery:
    external: true

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped

    networks:
      - discovery

    ports:
      - 3000:3000

    env_file: stack.env

    volumes:
      - ${SERVICE_DIR}/config:/app/config
      - ${SERVICE_DIR}/icons:/app/public/icons

    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.homepage.rule=Host(`${SERVICE_URL}`)'
      - 'traefik.http.routers.homepage.entrypoints=websecure'
      - 'traefik.http.routers.homepage.tls=true'
      - 'traefik.http.services.homepage.loadBalancer.server.port=3000'
      - 'traefik.docker.network=discovery'
