---
networks:
  discovery:
    external: true

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped

    networks:
      - discovery

    ports:
      - 3000:3000

    environment:
      - LOG_LEVEL=info
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - HOMEPAGE_VAR_PIHOLE_URL_1=${HOMEPAGE_VAR_PIHOLE_URL_1}
      - HOMEPAGE_VAR_PIHOLE_API_URL_1=${HOMEPAGE_VAR_PIHOLE_API_URL_1}
      - HOMEPAGE_VAR_PIHOLE_API_KEY_1=${HOMEPAGE_VAR_PIHOLE_API_KEY_1}
      - HOMEPAGE_VAR_PIHOLE_URL_2=${HOMEPAGE_VAR_PIHOLE_URL_2}
      - HOMEPAGE_VAR_PIHOLE_API_URL_2=${HOMEPAGE_VAR_PIHOLE_API_URL_2}
      - HOMEPAGE_VAR_PIHOLE_API_KEY_2=${HOMEPAGE_VAR_PIHOLE_API_KEY_2}
      - HOMEPAGE_VAR_TRAEFIK_URL=${HOMEPAGE_VAR_TRAEFIK_URL}
      - HOMEPAGE_VAR_TRAEFIK_USER=${HOMEPAGE_VAR_TRAEFIK_USER}
      - HOMEPAGE_VAR_TRAEFIK_PASSWORD=${HOMEPAGE_VAR_TRAEFIK_PASSWORD}
      - HOMEPAGE_VAR_PIKVM_URL=${HOMEPAGE_VAR_PIKVM_URL}
      - HOMEPAGE_VAR_IPMI_1_URL=${HOMEPAGE_VAR_IPMI_1_URL}
      - HOMEPAGE_VAR_KVM_URL=${HOMEPAGE_VAR_KVM_URL}
      - HOMEPAGE_VAR_HOME_ASSISTANT_URL=${HOMEPAGE_VAR_HOME_ASSISTANT_URL}
      - HOMEPAGE_VAR_HOME_ASSISTANT_API_KEY=${HOMEPAGE_VAR_HOME_ASSISTANT_API_KEY}
      - HOMEPAGE_VAR_UPTIME_KUMA_URL=${HOMEPAGE_VAR_UPTIME_KUMA_URL}
      - HOMEPAGE_VAR_UPTIME_ROBOT_API_KEY=${HOMEPAGE_VAR_UPTIME_ROBOT_API_KEY}
      - HOMEPAGE_VAR_PIALERT_URL=${HOMEPAGE_VAR_PIALERT_URL}
      - HOMEPAGE_VAR_NETBOX_URL=${HOMEPAGE_VAR_NETBOX_URL}
      - HOMEPAGE_VAR_NETDATA_URL=${HOMEPAGE_VAR_NETDATA_URL}
      - HOMEPAGE_VAR_WOL_URL=${HOMEPAGE_VAR_WOL_URL}
      - HOMEPAGE_VAR_NETBOOT_URL=${HOMEPAGE_VAR_NETBOOT_URL}
      - HOMEPAGE_VAR_NUT_URL=${HOMEPAGE_VAR_NUT_URL}
      - HOMEPAGE_VAR_SEMAPHORE_URL=${HOMEPAGE_VAR_SEMAPHORE_URL}
      - HOMEPAGE_VAR_SWITCH_1_URL=${HOMEPAGE_VAR_SWITCH_1_URL}
      - HOMEPAGE_VAR_SWITCH_2_URL=${HOMEPAGE_VAR_SWITCH_2_URL}
      - HOMEPAGE_VAR_SWITCH_3_URL=${HOMEPAGE_VAR_SWITCH_3_URL}
      - HOMEPAGE_VAR_SWITCH_4_URL=${HOMEPAGE_VAR_SWITCH_4_URL}
      - HOMEPAGE_VAR_SWITCH_5_URL=${HOMEPAGE_VAR_SWITCH_5_URL}
      - HOMEPAGE_VAR_SWITCH_6_URL=${HOMEPAGE_VAR_SWITCH_6_URL}
      - HOMEPAGE_VAR_SWITCH_7_URL=${HOMEPAGE_VAR_SWITCH_7_URL}
      - HOMEPAGE_VAR_SWITCH_8_URL=${HOMEPAGE_VAR_SWITCH_8_URL}
      - HOMEPAGE_VAR_OMADA_URL=${HOMEPAGE_VAR_OMADA_URL}
      - HOMEPAGE_VAR_ROUTER_1_URL=${HOMEPAGE_VAR_ROUTER_1_URL}
      - HOMEPAGE_VAR_ROUTER_2_URL=${HOMEPAGE_VAR_ROUTER_2_URL}
      - HOMEPAGE_VAR_PROXMOX_USER=${HOMEPAGE_VAR_PROXMOX_USER}
      - HOMEPAGE_VAR_PROXMOX_API_KEY=${HOMEPAGE_VAR_PROXMOX_API_KEY}
      - HOMEPAGE_VAR_PROXMOX_URL_1=${HOMEPAGE_VAR_PROXMOX_URL_1}
      - HOMEPAGE_VAR_PROXMOX_URL_IP_1=${HOMEPAGE_VAR_PROXMOX_URL_IP_1}
      - HOMEPAGE_VAR_PROXMOX_URL_2=${HOMEPAGE_VAR_PROXMOX_URL_2}
      - HOMEPAGE_VAR_PROXMOX_URL_IP_2=${HOMEPAGE_VAR_PROXMOX_URL_IP_2}
      - HOMEPAGE_VAR_PROXMOX_URL_3=${HOMEPAGE_VAR_PROXMOX_URL_3}
      - HOMEPAGE_VAR_PROXMOX_URL_IP_3=${HOMEPAGE_VAR_PROXMOX_URL_IP_3}
      - HOMEPAGE_VAR_PROXMOX_BACKUP_SERVER_URL=${HOMEPAGE_VAR_PROXMOX_BACKUP_SERVER_URL}
      - HOMEPAGE_VAR_PROXMOX_BACKUP_SERVER_IP=${HOMEPAGE_VAR_PROXMOX_BACKUP_SERVER_IP}
      - HOMEPAGE_VAR_PROXMOX_BACKUP_SERVER_USER=${HOMEPAGE_VAR_PROXMOX_BACKUP_SERVER_USER}
      - HOMEPAGE_VAR_PROXMOX_BACKUP_SERVER_SECRET=${HOMEPAGE_VAR_PROXMOX_BACKUP_SERVER_SECRET}
      - HOMEPAGE_VAR_PORTAINER_URL=${HOMEPAGE_VAR_PORTAINER_URL}
      - HOMEPAGE_VAR_SYNOLOGY_RACK_URL=${HOMEPAGE_VAR_SYNOLOGY_RACK_URL}
      - HOMEPAGE_VAR_TRUENAS_URL=${HOMEPAGE_VAR_TRUENAS_URL}
      - HOMEPAGE_VAR_TRUENAS_API_KEY=${HOMEPAGE_VAR_TRUENAS_API_KEY}
      - HOMEPAGE_VAR_MINIO_URL=${HOMEPAGE_VAR_MINIO_URL}
      - HOMEPAGE_VAR_LONGHORN_URL=${HOMEPAGE_VAR_LONGHORN_URL}
      - HOMEPAGE_VAR_PAPERLESS_URL=${HOMEPAGE_VAR_PAPERLESS_URL}
      - HOMEPAGE_VAR_PAPERLESS_TOKEN=${HOMEPAGE_VAR_PAPERLESS_TOKEN}
      - HOMEPAGE_VAR_SYNCTHING_URL=${HOMEPAGE_VAR_SYNCTHING_URL}
      - HOMEPAGE_VAR_NEXTCLOUD_URL=${HOMEPAGE_VAR_NEXTCLOUD_URL}
      - HOMEPAGE_VAR_ARCHIVE_BOX_URL=${HOMEPAGE_VAR_ARCHIVE_BOX_URL}      
      - HOMEPAGE_VAR_PLEX_NAS_URL=${HOMEPAGE_VAR_PLEX_NAS_URL}
      - HOMEPAGE_VAR_PLEX_NAS_API_TOKEN=${HOMEPAGE_VAR_PLEX_NAS_API_TOKEN}
      - HOMEPAGE_VAR_TAUTULLI_URL=${HOMEPAGE_VAR_TAUTULLI_URL}
      - HOMEPAGE_VAR_TAUTULLI_API_KEY=${HOMEPAGE_VAR_TAUTULLI_API_KEY}
      - HOMEPAGE_VAR_JELLYFIN_URL=${HOMEPAGE_VAR_JELLYFIN_URL}
      - HOMEPAGE_VAR_JELLYFIN_API_KEY=${HOMEPAGE_VAR_JELLYFIN_API_KEY}
      - HOMEPAGE_VAR_LIDARR_URL=${HOMEPAGE_VAR_LIDARR_URL}
      - HOMEPAGE_VAR_PROWLARR_URL=${HOMEPAGE_VAR_PROWLARR_URL}
      - HOMEPAGE_VAR_PROWLARR_API_KEY=${HOMEPAGE_VAR_PROWLARR_API_KEY}
      - HOMEPAGE_VAR_RADARR_URL=${HOMEPAGE_VAR_RADARR_URL}
      - HOMEPAGE_VAR_RADARR_API_KEY=${HOMEPAGE_VAR_RADARR_API_KEY}
      - HOMEPAGE_VAR_SONARR_URL=${HOMEPAGE_VAR_SONARR_URL}
      - HOMEPAGE_VAR_SONARR_API_KEY=${HOMEPAGE_VAR_SONARR_API_KEY}
      - HOMEPAGE_VAR_BAZARR_URL=${HOMEPAGE_VAR_BAZARR_URL}
      - HOMEPAGE_VAR_BAZARR_API_KEY=${HOMEPAGE_VAR_BAZARR_API_KEY}
      - HOMEPAGE_VAR_OVERSEERR_URL=${HOMEPAGE_VAR_OVERSEERR_URL}
      - HOMEPAGE_VAR_OVERSEERR_API_KEY=${HOMEPAGE_VAR_OVERSEERR_API_KEY}
      - HOMEPAGE_VAR_DELUGE_URL=${HOMEPAGE_VAR_DELUGE_URL}
      - HOMEPAGE_VAR_DELUGE_WEBUI_PWD=${HOMEPAGE_VAR_DELUGE_WEBUI_PWD}
      - HOMEPAGE_VAR_QBITTORRENT_URL=${HOMEPAGE_VAR_QBITTORRENT_URL}
      - HOMEPAGE_VAR_QBITTORRENT_USER=${HOMEPAGE_VAR_QBITTORRENT_USER}
      - HOMEPAGE_VAR_QBITTORRENT_PWD=${HOMEPAGE_VAR_QBITTORRENT_PWD}
      - HOMEPAGE_VAR_TDARR_URL=${HOMEPAGE_VAR_TDARR_URL}
      - HOMEPAGE_VAR_UPS_1_URL=${HOMEPAGE_VAR_UPS_1_URL}
      - HOMEPAGE_VAR_PDU_1_URL=${HOMEPAGE_VAR_PDU_1_URL}
      - HOMEPAGE_VAR_GROWATT_SERVER_URL=${HOMEPAGE_VAR_GROWATT_SERVER_URL}
      - HOMEPAGE_VAR_SOLAR_ASSISTANT_URL=${HOMEPAGE_VAR_SOLAR_ASSISTANT_URL}
      - HOMEPAGE_VAR_SNIPEIT_URL=${HOMEPAGE_VAR_SNIPEIT_URL}

    volumes:
      - ${SERVICE_DIR}/config:/app/config
      - ${SERVICE_DIR}/icons:/app/public/icons

    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.homepage.rule=Host(`${SERVICE_URL}`)'
      - 'traefik.http.routers.homepage.entrypoints=websecure'
      - 'traefik.http.routers.homepage.tls=true'
      - 'traefik.http.services.homepage.loadBalancer.server.port=3000'
      - 'traefik.docker.network=discovery'