---
networks:
  media-net:
    external: true

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped

    networks:
      - media-net

    ports:
      - "8989:8989" # port mapping

    # network_mode: "service:gluetun"
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SERVICE_DIR}:/config
      - ${REMOTE_DATA_DIR}/data:/data

    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:8989/sonarr/ping"]
      interval: 30s
      retries: 10
