services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always

    environment:
      - TZ=Asia/Colombo
      - WATCHTOWER_TIMEOUT=60
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      # - WATCHTOWER_POLL_INTERVAL=36000
      #- WATCHTOWER_SCHEDULE=0 0 9 * * *
      #- WATCHTOWER_DEBUG=true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
