---
networks:
  media-net:
    external: true
    
services:
  bazarr: 
    image: lscr.io/linuxserver/bazarr:latest 
    container_name: bazarr 
    restart: unless-stopped 
      
    ports: 
      - 6767:6767 

    networks:
      - media-net
  
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}

    volumes:
      - /etc/localtime:/etc/localtime:ro    
      - ${SERVICE_DIR}:/config
      - ${REMOTE_DATA_DIR}:/data/media