---
services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:4
    restart: unless-stopped

    network_mode: host

    ports:
      - 8090:8090

    environment:
      - TZ=Asia/Colombo # Set container timezone for cron schedules
      #   - UPSNAP_INTERVAL=@every 10s # Sets the interval in which the devices are pinged
      - UPSNAP_SCAN_RANGE=172.16.20.0/24 # Scan range is used for device discovery on local network
      #   - UPSNAP_SCAN_TIMEOUT=500ms # Scan timeout is nmap's --host-timeout value to wait for devices (https://nmap.org/book/man-performance.html)
      - UPSNAP_PING_PRIVILEGED=true # Set to false if you don't have root user permissions
      - UPSNAP_WEBSITE_TITLE=TheInquisitive WOL

    # dns is used for name resolution during network scan
    dns:
      - 172.16.20.6

    # # you can change the listen ip:port inside the container like this:
    # entrypoint: /bin/sh -c "./upsnap serve --http 0.0.0.0:5000"
    # # or install custom packages for shutdown
    # entrypoint: /bin/sh -c "apk update && apk add --no-cache <YOUR_PACKAGE> && rm -rf /var/cache/apk/* && ./upsnap serve --http 0.0.0.0:8090"
    healthcheck:
      test: curl -fs "http://localhost:8090/api/health" || exit 1
      interval: 10s

    volumes:
      - ${SERVICE_DIR}/data:/app/pb_data
