---
networks:
  discovery:
    external: true

services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    restart: unless-stopped

    networks:
      - discovery

    ports:
      - 3000:3000 # optional, destination should match ${WEB_APP_PORT} variable above.
      - 69:69/udp
      - 8080:80 # optional, destination should match ${NGINX_PORT} variable above.

    environment:
      # - MENU_VERSION=2.0.47 # optional
      - NGINX_PORT=80 # optional
      - WEB_APP_PORT=3000 # optional

    volumes:
      - ${SERVICE_DIR}/config:/config # optional
      - ${SERVICE_DIR}/assets:/assets # optional

    # labels:
    #   - 'traefik.enable=true'
    #   - 'traefik.http.routers.netboot.rule=Host(`${SERVICE_URL}`)'
    #   - 'traefik.http.routers.netboot.entrypoints=websecure'
    #   - 'traefik.http.routers.netboot.tls=true'
    #   - 'traefik.http.services.netboot.loadBalancer.server.port=3000'
