---
networks:
  discovery:
    external: true

services:
  portainer:
    image: portainer/portainer-ce

    container_name: portainer

    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

    networks:
      - discovery

    ports:
      - 9443:9443

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data

    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.portainer.entrypoints=web'
      - 'traefik.http.routers.portainer.rule=Host(`${SERVICE_URL}`)'
      - 'traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.portainer.middlewares=portainer-https-redirect'
      - 'traefik.http.routers.portainer-secure.entrypoints=websecure'
      - 'traefik.http.routers.portainer-secure.rule=Host(`${SERVICE_URL}`)'
      - 'traefik.http.routers.portainer-secure.tls=true'
      - 'traefik.http.routers.portainer-secure.service=portainer'
      - 'traefik.http.services.portainer.loadbalancer.server.port=9000'
      - 'traefik.docker.network=discovery'

volumes:
  portainer_data:
