services:
  # gluetun:
  #   image: qmcgaw/gluetun
  #   container_name: gluetun
  #   # line above must be uncommented to allow external containers to connect.
  #   # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
  #   cap_add:
  #     - NET_ADMIN
  #   devices:
  #     - /dev/net/tun:/dev/net/tun
  #   ports:
  #     - 6881:6881
  #     - 6881:6881/udp
  #     - 8085:8085 # qbittorrent
  #     - 9117:9117 # Jackett
  #     - 8989:8989 # Sonarr
  #     - 9696:9696 # Prowlarr
  #   volumes:
  #     - /home/ubuntu/docker/arr-stack:/gluetun
  #   environment:
  #     # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
  #     - VPN_SERVICE_PROVIDER=nordvpn
  #     - VPN_TYPE=wireguard
  #     # OpenVPN:
  #     # - OPENVPN_USER=
  #     # - OPENVPN_PASSWORD=
  #     # Wireguard:
  #     - WIREGUARD_PRIVATE_KEY=<YOUR_PRIVATE_KEY> # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/nordvpn.md#obtain-your-wireguard-private-key
  #     - WIREGUARD_ADDRESSES=10.5.0.2/32
  #     # Timezone for accurate log times
  #     - TZ=Europe/London
  #     # Server list updater
  #     # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
  #     - UPDATER_PERIOD=24h

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped

    ports:
      - '9696:9696'

    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}

    volumes:
      - ${SERVICE_DIR}/prowlarr:/config

    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://127.0.0.1:9696/prowlarr/ping']
      interval: 30s
      retries: 10

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped

    ports:
      - '8989:8989' # port mapping

    # network_mode: "service:gluetun"
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}

    volumes:
      - ${SERVICE_DIR}/sonarr:/config
      - ${SERVICE_DIR}/data:/data

    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://127.0.0.1:8989/sonarr/ping']
      interval: 30s
      retries: 10

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped

    ports:
      - '7878:7878' # port mapping

    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}

    volumes:
      - ${SERVICE_DIR}/radarr:/config
      - ${SERVICE_DIR}/data:/data

    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://127.0.0.1:7878/radarr/ping']
      interval: 30s
      retries: 10

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped

    # depends_on:
    #   - gluetun
    ports:
      - '8085:8085' # port mapping

    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8085

    volumes:
      - ${SERVICE_DIR}/qbittorrent:/config
      - ${SERVICE_DIR}/data:/downloads

    healthcheck:
      # Container may fail if the PIA's token expired, so mark as unhealthy when there is no internet connection
      # see: https://github.com/qdm12/gluetun/issues/641#issuecomment-933856220
      test: ['CMD', 'curl', '--fail', 'http://127.0.0.1:8080', 'https://google.com']
      interval: 30s
      retries: 10
