---
networks:
  media-net:
    external: true

services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC

    ports:
      - 8686:8686

    volumes:
      - ${SERVICE_DIR}/config:/config
      - ${REMOTE_DATA_DIR}/data/:/data
